// src/App.tsx
import React from 'react';
import './styles/App.css';
import './styles/player.css';

function App() {
    return <div id="playerUI" style={{display: 'block'}}>
        <div id="player" style={{display: 'block'}}>
            <video id="streamingVideo">
                <source src="" type="video/mp4" />
            </video>
        </div>
    </div>
}

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'Streaming UI';
}

<div id="playerUI" style="{display: block;}">
  <div id="player" style="{display: block}">
    <video id="streamingVideo">
      <source src="" type="video/mp4"/>
    </video>
  </div>
</div>
